version: 0.0
os: linux
files:
  - source: target/sportthon.jar
    destination: /home/ubuntu/app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 30
      runas: root

  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 30
      runas: root

  ApplicationStart:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root
