version: 0.0
os: linux
files:
  - source: target/sportthon.jar
    destination: /home/ubuntu/app

hooks:
  ApplicationStop:
    - location: stop_server.sh
      timeout: 60
      runas: root
  BeforeInstall:
    - location: before_install.sh
      timeout: 60
      runas: root
  AfterInstall:
    - location: after_install.sh
      timeout: 60
      runas: root
  ApplicationStart:
    - location: start_server.sh
      timeout: 60
      runas: root
  ValidateService:
    - location: validate.sh
      timeout: 60
      runas: root
