version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - if [ -x "$(command -v apt-get)" ]; then apt-get update && apt-get install -y openjdk-17-jdk; fi
      - echo "Downloading Maven..."
      - rm -f /tmp/maven.tar.gz
      - curl -L -o /tmp/maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
      # Validate tarball integrity
      - echo "a1b3c9d5e6f3..." > /tmp/maven-checksum.txt # Replace with the actual checksum
      - sha512sum /tmp/maven.tar.gz | grep -f /tmp/maven-checksum.txt || (echo "Checksum mismatch. Exiting."; exit 1)
      - sudo mkdir -p /opt
      - sudo tar -xzf /tmp/maven.tar.gz -C /opt
      - export PATH=$PATH:/opt/apache-maven-3.9.5/bin
      - mvn -version
  pre_build:
    commands:
      - echo "Cleaning up previous builds..."
      - mvn clean
  build:
    commands:
      - echo "Building the application..."
      - mvn package -DskipTests
  post_build:
    commands:
      - echo "Renaming the JAR file for deployment..."
      - mv target/*.jar app.jar
artifacts:
  files:
    - app.jar
  discard-paths: yes
  base-directory: target
