version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - if [ -x "$(command -v apt-get)" ]; then apt-get update && apt-get install -y openjdk-17-jdk; fi
      - echo "Downloading and extracting Maven..."
      - curl -L -o /tmp/maven.tar.gz https://archive.apache.org/dist/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
      - mkdir -p /opt/maven
      - tar -xzf /tmp/maven.tar.gz -C /opt/maven --strip-components=1
      - export PATH=$PATH:/opt/maven/bin
      - echo "Verifying Maven installation..."
      - mvn -version
  pre_build:
    commands:
      - echo "Cleaning previous builds..."
      - mvn clean
  build:
    commands:
      - echo "Building the application..."
      - mvn clean install -DskipTests -X || (echo "Maven build failed. Please check the logs for details." && exit 1)
  post_build:
    commands:
      - echo "Listing target directory contents..."
      - ls -lh target/
      - echo "Checking if any .jar file exists in the target directory..."
      - find target/ -name "*.jar"
      - echo "Renaming JAR for deployment..."
      - mv target/*.jar app.jar || (echo "No JAR file found. Build might have failed." && exit 1)
       - echo "Uploading JAR to S3..."
    - aws s3 cp app.jar s3://stylrax-123/code-build/app.jar
artifacts:
  files:
    - app.jar
  discard-paths: yes
  base-directory: target
