version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y java-17-openjdk-devel
      - curl -L -o /tmp/maven.tar.gz https://dlcdn.apache.org/maven/maven-3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
      - tar -xzf /tmp/maven.tar.gz -C /opt
      - export PATH=$PATH:/opt/apache-maven-3.9.5/bin
      - mvn -version

  pre_build:
    commands:
      - mvn clean

  build:
    commands:
      - mvn package -DskipTests

  post_build:
    commands:
      - mv target/*.jar app.jar  # Check if the output is really in 'target/*.jar'

artifacts:
  files:
    - app.jar  # Ensure this matches the correct file path
  discard-paths: yes
  base-directory: target  # This should point to the directory containing the .jar
