version: 0.2

phases:
  install:
    commands:
      - echo "Installing Java 21..."
      - curl -L -o java21.rpm https://corretto.aws/downloads/latest/amazon-corretto-21-x64-linux-jdk.rpm
      - sudo rpm -i java21.rpm
      - export JAVA_HOME=/usr/lib/jvm/java-21-amazon-corretto
      - export PATH=$JAVA_HOME/bin:$PATH
      - java -version
      - mvn --version
      - echo "Making scripts executable..."
      - chmod +x scripts/*.sh

  build:
    commands:
      - echo Build started on `date`
      - mvn clean package -DskipTests
      - cp target/sportthon-0.0.1-SNAPSHOT.jar sportthon.jar

artifacts:
  files:
    - sportthon.jar
    - appspec.yml
    - scripts/**
  discard-paths: no
