version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."
      - yum install -y java-17-openjdk-devel  # Install Java 17 (adjust based on your JDK version)
      - curl -L -o /tmp/maven.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
      - tar -xzf /tmp/maven.tar.gz -C /opt
      - export PATH=$PATH:/opt/apache-maven-3.9.5/bin  # Add Maven to PATH
      - mvn -version  # Verify Maven installation
  pre_build:
    commands:
      - echo "Preparing build..."
      - mvn clean  # Clean previous builds
  build:
    commands:
      - echo "Building the application..."
      - mvn package -DskipTests  # Package the application without running tests
  post_build:
    commands:
      - echo "Running post-build actions..."
      - mv target/*.jar app.jar  # Rename the packaged JAR file for easier deployment
artifacts:
  files:
    - app.jar  # Include the built JAR file
    - buildspec.yml  # Include the buildspec file for future reference
  discard-paths: yes
  base-directory: target  # Base directory for artifacts
